### ISSUE TITLE
Refused to load the script

### ISSUE THREAD

**Issue by sadue** [bhargav1996/Fb-Auto-tools#10]
I tried to use this script on chrome console, but the following error occur;

> VM331:2 Refused to load the script 'https://raw.github.com/bhargav1996/Fb-Auto-tools/master/message-maker.js' because it violates the following Content Security Policy directive: "script-src _.facebook.com *.fbcdn.net *.facebook.net *.google-analytics.com *.virtualearth.net *.google.com 127.0.0.1:_ _.spotilocal.com:_ 'unsafe-inline' 'unsafe-eval' fbstatic-a.akamaihd.net fbcdn-static-b-a.akamaihd.net _.atlassolutions.com blob: chrome-extension://lifbcibllhkdhoafpjfnlhfpfgnpldfl https://_.facebook.com".

**Comment by bhargav1996** [comment]
brother scripts are now a days been ban and plus do not use them you might got ban from fb 
plus i haven't updated from years 
so it's best to say they are outdated
